### ISSUE TITLE
Prover dies and verification is inconclusive

### ISSUE THREAD

**Issue by pfons** [Microsoft/Ironclad#2]
Verifying the current Ironfleet head (c07cd96) from the console produces several “inconclusive” verification errors.

Here is an example of the errors produced:

```
src\Dafny\Distributed\Common\Logic\Temporal\Rules.i.dfy(191,10): Verification inconclusive (CheckWellformed$$_9_Temporal____Rules__i.__default.Lemma__AlwaysImpliesLaterAlways)
Prover error: Error setting 'smt.arith.nl', reason: unknown option.
Prover error: ERROR: invalid INI file
Prover error: Prover died
```

If the Z3 binary (version 4.1) included with Ironfleet is replaced with a more recent version of Z3 that I had around (version 4.4.1 - 64 bit) everything works correctly on my machine.

**Comment by parno** [comment]
Hi Pedro,

Thanks for your report.  Yes, all of the code is meant to be verified with Z3 version 4.4.1.  I think that's what used to be checked in before I accepted your previous pull request to update Z3's architecture, which I should have checked more closely.  I'll post another update to the binary shortly.  

Bryan

**Comment by parno** [comment]
Commit 04cc923392c0ac19fd31f67e5c436cc422b73454 now uses the 32-bit version of Z3 v4.4.1.  Let us know if you still see surprising issues.
